trigger:
- main

pool: 'default'

steps:
# Étape 1 : Télécharger le code source depuis GitHub
- checkout: self
  displayName: "Télécharger le code source depuis GitHub"

# Étape 2 : Créer le groupe de ressources
- task: AzureCLI@2
  displayName: "Créer le groupe de ressources"
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name TP2C --location canadacentral

# Étape 3 : Vérifier et supprimer les déploiements précédents (éviter les conflits)
- task: AzureCLI@2
  displayName: "Supprimer les déploiements précédents (si existants)"
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group delete --resource-group TP2C --name template || echo "Aucun déploiement précédent trouvé."

# Étape 4 : Créer le compte de stockage
- task: AzureCLI@2
  displayName: "Créer le compte de stockage"
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage account create `
        --name fonctionappvijo2grouzaw `
        --resource-group TP2C `
        --location canadacentral `
        --sku Standard_LRS

# Étape 5 : Créer le Log Analytics Workspace
- task: AzureCLI@2
  displayName: "Créer le Log Analytics Workspace"
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az monitor log-analytics workspace create `
        --resource-group TP2C `
        --workspace-name DefaultWorkspace-4752c137-48fe-4a21-ac6e-435c1d51dbe9 `
        --location canadacentral

# Étape 6 : Valider le template ARM
- task: AzureCLI@2
  displayName: "Valider le template ARM"
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group validate `
        --resource-group TP2C `
        --template-file "$(Build.SourcesDirectory)\template.json" `
        --parameters "$(Build.SourcesDirectory)\parameters.json"

# Étape 7 : Déployer le template ARM
- task: AzureCLI@2
  displayName: "Déployer le template ARM"
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create `
        --resource-group TP2C `
        --template-file "$(Build.SourcesDirectory)\template.json" `
        --parameters "$(Build.SourcesDirectory)\parameters.json" `
        --verbose
