trigger:
  - main

pool: 'default'

variables:
  AzureAppFunction: 'AzureResourceTP2/FunctionApp/Function'
  AzureFunctionAppName: 'TP2GuroFunction'
  StorageAccountName: 'tp2storageaccount$(Build.BuildId)'
  Location: 'Canada Central'

stages:
  - stage: DeployInfrastructure
    displayName: 'Deploy Infrastructure'
    jobs:
      - job: DeployInfrastructure
        displayName: 'Infrastructure Deployment'
        steps:
          # Création ou vérification du groupe de ressources tp2SC
          - task: AzureCLI@2
            displayName: 'Check or Create Resource Group tp2SC'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create ^
                  --name tp2SC ^
                  --location "$(Location)"

          # Création ou vérification du groupe de ressources DefaultResourceGroup-CCAN
          - task: AzureCLI@2
            displayName: 'Check or Create Resource Group DefaultResourceGroup-CCAN'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create ^
                  --name DefaultResourceGroup-CCAN ^
                  --location "$(Location)"

          # Création du compte de stockage
          - task: AzureCLI@2
            displayName: 'Create Storage Account'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account create ^
                  --name $(StorageAccountName) ^
                  --resource-group tp2SC ^
                  --location "$(Location)" ^
                  --sku Standard_LRS

          # Création de l'Action Group
          - task: AzureCLI@2
            displayName: 'Create Action Group'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az monitor action-group create ^
                  --resource-group DefaultResourceGroup-CCAN ^
                  --name "ApplicationInsightsSmartDetection" ^
                  --short-name "SmartDetect"

          # Création de l'instance Application Insights
          - task: AzureCLI@2
            displayName: 'Create Application Insights'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az monitor app-insights component create ^
                  --app fonctionappvijo ^
                  --location "$(Location)" ^
                  --resource-group tp2SC ^
                  --application-type web

          # Création de la Function App Plan
          - task: AzureCLI@2
            displayName: 'Create App Service Plan'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az appservice plan create ^
                  --name ASP-fonctionappvijogroup-96bd ^
                  --resource-group tp2SC ^
                  --location "$(Location)" ^
                  --sku Y1 ^
                  --is-linux false

          # Création de la Function App
          - task: AzureCLI@2
            displayName: 'Create Function App'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az functionapp create ^
                  --name $(AzureFunctionAppName) ^
                  --storage-account $(StorageAccountName) ^
                  --resource-group tp2SC ^
                  --consumption-plan-location "$(Location)" ^
                  --runtime dotnet ^
                  --runtime-version 7.0

          # Configuration des conteneurs pour Azure Functions
          - task: AzureCLI@2
            displayName: 'Configure Blob Containers'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage container create ^
                  --name azure-webjobs-hosts ^
                  --account-name $(StorageAccountName) ^
                  --public-access off

                az storage container create ^
                  --name azure-webjobs-secrets ^
                  --account-name $(StorageAccountName) ^
                  --public-access off

