trigger:
  - main

pool: 'default'

variables:
  AzureFunctionAppName: 'TP2GuroFunction'
  StorageAccountName: 'tp2storageaccount$(Build.BuildId)'
  ServiceBusNamespace: 'tp2servicebus$(Build.BuildId)'
  QueueName: 'tp2queue'
  Location: 'Canada Central'

stages:
  - stage: DeployInfrastructure
    displayName: 'Deploy Infrastructure'
    jobs:
      - job: DeployInfrastructure
        displayName: 'Infrastructure Deployment'
        steps:
          # Création du groupe de ressources
          - task: AzureCLI@2
            displayName: 'Create Resource Group'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name tp2SC --location "$(Location)"

          # Création du compte de stockage
          # Création du compte de stockage
          - task: AzureCLI@2
            displayName: 'Create Storage Account'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account create ^
                  --name "$(StorageAccountName)" ^
                  --resource-group tp2SC ^
                  --location "$(Location)" ^
                  --sku Standard_LRS


          # Création du Service Bus et de la queue
          - task: AzureCLI@2
            displayName: 'Create Service Bus and Queue'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az servicebus namespace create \
                  --name $(ServiceBusNamespace) \
                  --resource-group tp2SC \
                  --location "$(Location)" \
                  --sku Basic
                
                az servicebus queue create \
                  --name $(QueueName) \
                  --namespace-name $(ServiceBusNamespace) \
                  --resource-group tp2SC

          # Création de la Function App
          - task: AzureCLI@2
            displayName: 'Create Function App'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az functionapp create \
                  --name $(AzureFunctionAppName) \
                  --storage-account $(StorageAccountName) \
                  --resource-group tp2SC \
                  --consumption-plan-location "eastus" \
                  --runtime dotnet \
                  --runtime-version 8 \
                  --functions-version 4

  - stage: DeployFunctions
    displayName: 'Deploy Azure Functions'
    dependsOn: DeployInfrastructure
    jobs:
      - job: DeployFunctions
        displayName: 'Deploy Functions'
        steps:
          # Build and deploy BlobManipulation Function
          - task: DotNetCoreCLI@2
            displayName: 'Publish BlobManipulation Function'
            inputs:
              command: 'publish'
              projects: '$(Build.SourcesDirectory)/TP2deploiement/BlobManipulation/BlobManipulation.csproj'
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/BlobManipulation'

          - task: AzureFunctionApp@2
            displayName: 'Deploy BlobManipulation Function'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              appType: 'functionApp'
              appName: $(AzureFunctionAppName)
              package: '$(Build.ArtifactStagingDirectory)/BlobManipulation/**/*.zip'

          # Build and deploy Service Bus Processor Function
          - task: DotNetCoreCLI@2
            displayName: 'Publish Azure Bus Function'
            inputs:
              command: 'publish'
              projects: '$(Build.SourcesDirectory)/TP2deploiement/AzureBus/AzureBus.csproj'
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/AzureBus'

          - task: AzureFunctionApp@2
            displayName: 'Deploy Azure Bus Function'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              appType: 'functionApp'
              appName: $(AzureFunctionAppName)
              package: '$(Build.ArtifactStagingDirectory)/AzureBus/**/*.zip'
