trigger:
- main

pool: 'default'

steps:
# Étape 1 : Télécharger le code source depuis GitHub
- checkout: self
  displayName: "Télécharger le code source depuis GitHub"

# Étape 2 : Validation du template ARM
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group validate \
        --resource-group TP2C \
        --template-file $(Build.SourcesDirectory)/TP2deploiement/template.json \
        --parameters $(Build.SourcesDirectory)/TP2deploiement/parameters.json

# Étape 3 : Déploiement du template ARM
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --resource-group TP2C \
        --template-file $(Build.SourcesDirectory)/TP2deploiement/template.json \
        --parameters $(Build.SourcesDirectory)/TP2deploiement/parameters.json \
        --verbose
