trigger:
  - main

pool: 'default'

variables:
  AzureAppFunction: 'AzureResourceTP2/BlobManipulation'
  StorageAccountName: 'tp2storageaccount$(Build.BuildId)'
  ServiceBusNamespace: 'tp2servicebus$(Build.BuildId)'
  QueueName: 'tp2queue'
  AzureFunctionAppName: 'TP2GuroFunction'
  Location: 'Canada Central'

stages:
  - stage: DeployInfrastructure
    displayName: 'Deploy Infrastructure'
    jobs:
      - job: DeployInfrastructure
        displayName: 'Infrastructure Deployment'
        steps:
          # Création du groupe de ressources
          - task: AzureCLI@2
            displayName: 'Create Resource Group'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name tp2SC --location "$(Location)"

          # Création du Storage Account
          - task: AzureCLI@2
            displayName: 'Create Storage Account'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account create --name $(StorageAccountName) --resource-group tp2SC --location "$(Location)" --sku Standard_LRS

          # Création du Service Bus
          - task: AzureCLI@2
            displayName: 'Create Service Bus Namespace and Queue'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az servicebus namespace create --name $(ServiceBusNamespace) --resource-group tp2SC --location "$(Location)"
                az servicebus queue create --name $(QueueName) --namespace-name $(ServiceBusNamespace) --resource-group tp2SC

  - stage: DeployBlobManipulation
    displayName: 'Deploy Blob Manipulation'
    dependsOn: DeployInfrastructure
    jobs:
      - job: DeployBlobManipulation
        displayName: 'Deploy Blob Manipulation App'
        steps:
          # Build and deploy Blob Manipulation App
          - task: DotNetCoreCLI@2
            displayName: 'Publish Blob Manipulation App'
            inputs:
              command: 'publish'
              projects: '$(Build.SourcesDirectory)/AzureResourceTP2/BlobManipulation/BlobManipulation.csproj'
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/BlobManipulation'
              publishWebProjects: false  # Désactive la détection automatique des projets web

          - task: AzureCLI@2
            displayName: 'Run Blob Manipulation App'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                dotnet $(Build.ArtifactStagingDirectory)/BlobManipulation/BlobManipulation.dll
