trigger:
  - main

pool: 'default'

variables:
  StorageAccountName: 'tp2storageaccount$(Build.BuildId)'
  ServiceBusNamespace: 'tp2servicebus$(Build.BuildId)'
  QueueName: 'tp2queue'
  AzureFunctionAppName: 'TP2GuroFunction'
  Location: 'Canada Central'

stages:
  - stage: DeployInfrastructure
    displayName: 'Deploy Infrastructure'
    jobs:
      - job: DeployInfrastructure
        displayName: 'Infrastructure Deployment'
        steps:
          # Création du groupe de ressources
          - task: AzureCLI@2
            displayName: 'Create Resource Group'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name tp2SC --location "$(Location)"

          # Création du Storage Account
          - task: AzureCLI@2
            displayName: 'Create Storage Account'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account create --name $(StorageAccountName) --resource-group tp2SC --location "$(Location)" --sku Standard_LRS

          # Création du Service Bus
          - task: AzureCLI@2
            displayName: 'Create Service Bus Namespace and Queue'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az servicebus namespace create --name $(ServiceBusNamespace) --resource-group tp2SC --location "$(Location)"
                az servicebus queue create --name $(QueueName) --namespace-name $(ServiceBusNamespace) --resource-group tp2SC

          # Déploiement de la Function App
          - task: AzureCLI@2
            displayName: 'Deploy Function App'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az functionapp create ^
                  --name $(AzureFunctionAppName) ^
                  --storage-account $(StorageAccountName) ^
                  --resource-group tp2SC ^
                  --consumption-plan-location "eastus" ^
                  --runtime dotnet ^
                  --runtime-version 8 ^
                  --functions-version 4

  - stage: DeployFunctions
    displayName: 'Deploy Azure Functions'
    dependsOn: DeployInfrastructure
    jobs:
      - job: DeployFunctions
        displayName: 'Deploy Functions'
        steps:
          # Build and deploy Blob Trigger Function
          - task: DotNetCoreCLI@2
            displayName: 'Publish Blob Trigger Function'
            inputs:
              command: 'publish'
              projects: 'BlobTriggerFunction/BlobTriggerFunction.csproj'
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/BlobTrigger'

          - task: AzureFunctionApp@2
            displayName: 'Deploy Blob Trigger Function'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              appType: 'functionApp'  # Ajout de la propriété appType
              appName: $(AzureFunctionAppName)
              package: '$(Build.ArtifactStagingDirectory)/BlobTrigger/**/*.zip'

          # Build and deploy Queue Trigger Function
          - task: DotNetCoreCLI@2
            displayName: 'Publish Queue Trigger Function'
            inputs:
              command: 'publish'
              projects: 'QueueTriggerFunction/QueueTriggerFunction.csproj'
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/QueueTrigger'

          - task: AzureFunctionApp@2
            displayName: 'Deploy Queue Trigger Function'
            inputs:
              azureSubscription: 'Azure subscription 1(2)(4752c137-48fe-4a21-ac6e-435c1d51dbe9)'
              appType: 'functionApp'  # Ajout de la propriété appType
              appName: $(AzureFunctionAppName)
              package: '$(Build.ArtifactStagingDirectory)/QueueTrigger/**/*.zip'

